# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_tring\deep_learning\新建文件夹\window-yolo\apps\UI\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1322, 795)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_add_view = QtWidgets.QPushButton(self.widget)
        self.button_add_view.setObjectName("button_add_view")
        self.horizontalLayout.addWidget(self.button_add_view)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1322, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_select_image = QtWidgets.QAction(MainWindow)
        self.action_select_image.setObjectName("action_select_image")
        self.action_select_video = QtWidgets.QAction(MainWindow)
        self.action_select_video.setObjectName("action_select_video")
        self.action_internet = QtWidgets.QAction(MainWindow)
        self.action_internet.setObjectName("action_internet")
        self.menu_file.addAction(self.action_select_image)
        self.menu_file.addAction(self.action_select_video)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_add_view.setText(_translate("MainWindow", "添加"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.action_select_image.setText(_translate("MainWindow", "选择图片"))
        self.action_select_video.setText(_translate("MainWindow", "选择视频"))
        self.action_internet.setText(_translate("MainWindow", "配置网络信号源"))
