# Generated by Django 4.1.4 on 2022-12-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detectView', '0002_detect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detect',
            new_name='DetectImg',
        ),
    ]
