# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_tring\deep_learning\garbage\app\UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.combox_select_weights = QtWidgets.QComboBox(self.centralwidget)
        self.combox_select_weights.setCurrentText("")
        self.combox_select_weights.setObjectName("combox_select_weights")
        self.gridLayout_2.addWidget(self.combox_select_weights, 0, 0, 1, 1)
        self.pushButton_statr_detect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_statr_detect.setObjectName("pushButton_statr_detect")
        self.gridLayout_2.addWidget(self.pushButton_statr_detect, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.widget = QtWidgets.QWidget(self.splitter_3)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_detect_labels = QtWidgets.QLabel(self.widget)
        self.label_detect_labels.setText("")
        self.label_detect_labels.setObjectName("label_detect_labels")
        self.gridLayout.addWidget(self.label_detect_labels, 0, 0, 1, 1)
        self.label_player = QtWidgets.QLabel(self.widget)
        self.label_player.setStyleSheet("font: 36pt \"Agency FB\";\n"
"background-color:rgb(234,234,234);")
        self.label_player.setAlignment(QtCore.Qt.AlignCenter)
        self.label_player.setObjectName("label_player")
        self.gridLayout.addWidget(self.label_player, 1, 0, 1, 1)
        self.label_res_msg = QtWidgets.QLabel(self.widget)
        self.label_res_msg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_res_msg.setObjectName("label_res_msg")
        self.gridLayout.addWidget(self.label_res_msg, 2, 0, 1, 1)
        self.textEdit_res_msg = QtWidgets.QTextEdit(self.widget)
        self.textEdit_res_msg.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textEdit_res_msg.setObjectName("textEdit_res_msg")
        self.gridLayout.addWidget(self.textEdit_res_msg, 3, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 12)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 5)
        self.horizontalLayout_2.addWidget(self.splitter_3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_select_image = QtWidgets.QAction(MainWindow)
        self.action_select_image.setObjectName("action_select_image")
        self.action_select_video = QtWidgets.QAction(MainWindow)
        self.action_select_video.setObjectName("action_select_video")
        self.menu.addAction(self.action_select_image)
        self.menu.addAction(self.action_select_video)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_statr_detect.setText(_translate("MainWindow", "启动模型"))
        self.label_player.setText(_translate("MainWindow", "无信号"))
        self.label_res_msg.setText(_translate("MainWindow", "信息栏"))
        self.textEdit_res_msg.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">尚未开始推理</p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action_select_image.setText(_translate("MainWindow", "选择图片"))
        self.action_select_video.setText(_translate("MainWindow", "选择视频"))
