# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_tring\deep_learning\garbage\app\UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_statr_detect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_statr_detect.setObjectName("pushButton_statr_detect")
        self.horizontalLayout.addWidget(self.pushButton_statr_detect)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_player = QtWidgets.QLabel(self.centralwidget)
        self.label_player.setStyleSheet("font: 36pt \"Agency FB\";\n"
"background-color:rgb(234,234,234);")
        self.label_player.setAlignment(QtCore.Qt.AlignCenter)
        self.label_player.setObjectName("label_player")
        self.verticalLayout.addWidget(self.label_player)
        self.label_res_msg = QtWidgets.QLabel(self.centralwidget)
        self.label_res_msg.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_res_msg.setObjectName("label_res_msg")
        self.verticalLayout.addWidget(self.label_res_msg)
        self.textEdit_res_msg = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_res_msg.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textEdit_res_msg.setObjectName("textEdit_res_msg")
        self.verticalLayout.addWidget(self.textEdit_res_msg)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_select_image = QtWidgets.QAction(MainWindow)
        self.action_select_image.setObjectName("action_select_image")
        self.action_select_video = QtWidgets.QAction(MainWindow)
        self.action_select_video.setObjectName("action_select_video")
        self.menu.addAction(self.action_select_image)
        self.menu.addAction(self.action_select_video)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_statr_detect.setText(_translate("MainWindow", "启动模型"))
        self.label_player.setText(_translate("MainWindow", "无信号"))
        self.label_res_msg.setText(_translate("MainWindow", "信息栏"))
        self.textEdit_res_msg.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">尚未开始推理</p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action_select_image.setText(_translate("MainWindow", "选择图片"))
        self.action_select_video.setText(_translate("MainWindow", "选择视频"))
