# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_tring\deep_learning\garbage\UI\view_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewForm(object):
    def setupUi(self, ViewForm):
        ViewForm.setObjectName("ViewForm")
        ViewForm.resize(415, 363)
        self.label_detect_labels_3 = QtWidgets.QLabel(ViewForm)
        self.label_detect_labels_3.setGeometry(QtCore.QRect(9, 9, 48, 16))
        self.label_detect_labels_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_detect_labels_3.setObjectName("label_detect_labels_3")
        self.label_player_3 = QtWidgets.QLabel(ViewForm)
        self.label_player_3.setGeometry(QtCore.QRect(9, 35, 144, 58))
        self.label_player_3.setStyleSheet("font: 36pt \"Agency FB\";\n"
"background-color:rgb(229, 229, 229);")
        self.label_player_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_player_3.setObjectName("label_player_3")
        self.label_res_msg_3 = QtWidgets.QLabel(ViewForm)
        self.label_res_msg_3.setGeometry(QtCore.QRect(9, 128, 36, 16))
        self.label_res_msg_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_res_msg_3.setObjectName("label_res_msg_3")
        self.textEdit_res_msg_3 = QtWidgets.QTextEdit(ViewForm)
        self.textEdit_res_msg_3.setGeometry(QtCore.QRect(9, 154, 256, 192))
        self.textEdit_res_msg_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textEdit_res_msg_3.setObjectName("textEdit_res_msg_3")
        self.pushButton_statr_detect_3 = QtWidgets.QPushButton(ViewForm)
        self.pushButton_statr_detect_3.setGeometry(QtCore.QRect(83, 99, 70, 23))
        self.pushButton_statr_detect_3.setObjectName("pushButton_statr_detect_3")
        self.combox_select_weights_3 = QtWidgets.QComboBox(ViewForm)
        self.combox_select_weights_3.setGeometry(QtCore.QRect(9, 99, 69, 20))
        self.combox_select_weights_3.setCurrentText("")
        self.combox_select_weights_3.setObjectName("combox_select_weights_3")

        self.retranslateUi(ViewForm)
        QtCore.QMetaObject.connectSlotsByName(ViewForm)

    def retranslateUi(self, ViewForm):
        _translate = QtCore.QCoreApplication.translate
        ViewForm.setWindowTitle(_translate("ViewForm", "Form"))
        self.label_detect_labels_3.setText(_translate("ViewForm", "检测目标"))
        self.label_player_3.setText(_translate("ViewForm", "无信号"))
        self.label_res_msg_3.setText(_translate("ViewForm", "信息栏"))
        self.textEdit_res_msg_3.setHtml(_translate("ViewForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">尚未开始推理</p></body></html>"))
        self.pushButton_statr_detect_3.setText(_translate("ViewForm", "启动模型"))
