# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_tring\deep_learning\garbage\UI\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1322, 795)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view_frame_gridLayout = QtWidgets.QGridLayout()
        self.view_frame_gridLayout.setObjectName("view_frame_gridLayout")
        self.horizontalLayout_2.addLayout(self.view_frame_gridLayout)
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1322, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_signal = QtWidgets.QMenu(self.menubar)
        self.menu_signal.setObjectName("menu_signal")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_select_image = QtWidgets.QAction(MainWindow)
        self.action_select_image.setObjectName("action_select_image")
        self.action_select_video = QtWidgets.QAction(MainWindow)
        self.action_select_video.setObjectName("action_select_video")
        self.action_internet = QtWidgets.QAction(MainWindow)
        self.action_internet.setObjectName("action_internet")
        self.menu_file.addAction(self.action_select_image)
        self.menu_file.addAction(self.action_select_video)
        self.menu_signal.addAction(self.action_internet)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_signal.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_signal.setTitle(_translate("MainWindow", "信号源"))
        self.action_select_image.setText(_translate("MainWindow", "选择图片"))
        self.action_select_video.setText(_translate("MainWindow", "选择视频"))
        self.action_internet.setText(_translate("MainWindow", "配置网络信号源"))
